""" This program can print the reverse-complement of a string. """

word = 'TACCAGCTCTCCAACCTATCAAGCGTGTCACCAAGCTGAGAGCTATCAAGTGGCCTATCGAGGGGTTAGCGTAGACTTTTCTCATAGGGGGTCCGGGAAGATGGACGCCAATTAAAGCACCATACGACGATGTGAACACTTCTGCCAGATAGATTATCAATTCTTGTAAGCGTAGCGATTACGCTCTACTGTATTTTATGATGGAGACACATGTTCTGCACGAGGCGCGTCTCAGAACTTCGGGAAACCACGGTAACATCCTTAGTTCGGGTCGGGGTAAACACCTAGACCCGCGTGGGGTAGATTTATCATATTGGGACAGAGCGAAGAGTGGTGAACCTAATTACAGTTGCCTTATCCTTACACTGGAAGGTAGGTCCTGAGTTAACGGTGTCGTACTACCCGACTGCTTAAAGCTGACGACACCATGGTAGACGTTTCGGTAGTGCCCCGCCGGTATGCGCTGACGGGTATTCCCTGCAACGGCACCTCACGTACGGGTTGATTAAGCTTCAGAGATCTAACCACACTAGGTGCGAGCAAAGGTAGTGGACGCCCCCGAAGCCCTCCCTGATGGTTAAGTTTTCATTCGGCTTTATATTGAAGGTTGCCACTTTAGGCTGGGTCACAAAAGATTTTCCTTCCTTAGGTCTAACGTGACGGACGTACACGCAGATAAACAGTGAAGCAATGACCGCCAAGGTCGGTACCGACAGCCCTGAGCGGCTGGAAGGCTGAATACTTACGGTTGGCCATGGGCACACCCCGTTTTGCAGGAGCAGTCTCTGTTGCGGTTCCAAGGGTGCTTGATCTCA'

def rc(strand):
    s = strand[::-1]
    new = ''
    for x in s:
        if x == 'A':
            new = new + 'T'
        elif x == 'T':
            new = new + 'A'
        elif x == 'G':
            new = new + 'C'
        else: 
            new = new + 'G'
    return new

print(rc(word))
            
    