""" This program displays the occurence counts of A G T C. """

s = 'ATCGACGCTTGGGAACATACCGAGATGCAATTCGGCGATCGCCCGGTACGGGCCGTGCATTGCTGGAGCACGCTGCATACTGGAGAACGTCAATGGCTGAGAACGTCCAGAAACAAGCCGCATACGAGCGCGGAATAACCATGGATCTCGTCTCGTTCATGGCAATGACAGGAGGCGATATCTAAAGAACTCCATATCTACTATGAAACCGACGCGAGCGGCGCGGACGCGGGATAAGCTAGCTGGAGATGTACGCTGATTTTCGTCGTTAAGAACAAGCGACCCTCCCGCCTCGTAAGTAAGTCCGTGAAGGCTCTTCATGCACGGCCTCTTGCCCGTAGCCATCGAGGCTGAAGCGTAGGACGTCAACCCAAGTGTGGGATCGAATGATAAGGCACATGATGAATCCCATTTTATGCACCCGCCTACGGAAGTGGATTCCGGGTTATGTTGGATGTGACCAACGTTGGCTTGCGATATAAGCTAGTAGGCCTCTCTACCCAAGAAGGCGCGTTTATTTTCCGGGTTCCAGTAAGTCCAACTGGATGTCCTCTAAGAATTCGCAGCGTTGCCTGATAAATAGAGATGAGTAAGTATGCCTGCACGCCACATGGTATGTGATAGGTTCCCCGTATGAGGACCCCTCGTGACGGCGACGCCATGATTTGGACTCTATCTCTAGTTAGGATGGTCACCAATACACTTATGTTTAGGCTCGCGGGTACTATAGATAAGCTATGTCGTAAGAACGACCTCACCATCGATCTGGTTCCCACAGCCGCATAAATCACGTACGCAGCTCCGACTGGAAGAGCGTTTACGTACTGTCCCGGGGGCTGCAGATGTTCCCTCTGTTTCTTTAGTATTCGGATAGATTTATGCGCATCATGAGGGTCTA'

def count(strand):
    countA = 0
    countC = 0
    countG = 0
    countT = 0
    for x in strand:
        if x == 'A':
            countA = countA + 1
        elif x == 'C':
            countC = countC + 1
        elif x == 'G':
            countG = countG + 1
        elif x == 'T':
            countT = countT + 1
    print(str(countA) + ' ' + str(countC) + ' ' + str(countG) + ' ' + str(countT))
count(s) # A C G T